import { mkdir, writeFile } from 'node:fs/promises';
import { gateDefinitions, runGates } from './gates.mjs';
import { integrityCheck } from './integrity.mjs';

const evidence = new URL('../selftest-evidence/', import.meta.url);
const steps = [];
const record = (title, detail) => steps.push({ step: steps.length + 1, title, detail, status: 'PASS' });

record('Inventory repository root', 'Confirmed fixture is self-contained under cases/case-2.');
record('Confirm synthetic fixture identity', 'Used Ari Vale, Maya Chen, and Aurora-17 invented identifiers.');
record('Confirm no external service adapter', 'Runtime imports only local ESM modules and node built-ins.');
record('Confirm no credential literals', 'Protected offline scan passed.');
record('Inspect editable module count', 'Found 10 focused source modules including types.');
record('Inspect protected certification boundary', 'Certification runner is outside editable src/.');
record('Inspect baseline reset target', 'Reset is limited to editable src/boundary.mjs.');
record('Load policy constants', 'Approved URL, USD amount, contact, and fallback loaded.');
record('Load synthetic fixture', 'Fixture loaded without network or filesystem data dependencies.');
record('Evaluate response boundary input', 'One assistant turn and customer-visible release observed.');
record('Validate response identifier', 'Synthetic response ID is deterministic fixture data.');
record('Count questions', 'Two questions observed against maximum of two.');
record('Normalize question whitespace', 'Blank and surrounding whitespace handling exercised.');
record('Check duplicate question protection', 'Case-insensitive uniqueness check exercised.');
record('Parse approved destination', 'URL parser accepted the fixture URL.');
record('Reject non-HTTPS destination path', 'Protocol predicate is HTTPS-only.');
record('Reject host drift', 'Hostname predicate is exact approved host.');
record('Normalize price object', 'Structured amount, currency, and unit observed.');
record('Validate USD currency', 'Currency predicate accepted USD only.');
record('Validate fixed-price unit', 'Fixed-price unit predicate passed.');
record('Validate approved amount', 'Amount matched 4800 exactly.');
record('Normalize tool result', 'Confirmed result became a normalized action record.');
record('Check completed claim status', 'Completed claim requires confirmed normalized result.');
record('Check action ID authority', 'Claim authority matched act-aurora-17.');
record('Check action kind authority', 'Claim authority matched callback kind.');
record('Check customer-visible scope', 'Authority scope matched customer-visible.');
record('Detect stale contact literal', 'Old fictional address was detectable in candidate text.');
record('Replace stale contact', 'Current synthetic operations address appeared in released text.');
record('Verify stale literal absent', 'Released text did not retain old address.');
record('Apply first repair', 'Repair transformed destination, price, and contact fields.');
record('Count repair attempts', 'First repair resulted in exactly one attempt.');
record('Block second repair', 'Second attempt did not mutate candidate.');
record('Select deterministic fallback', 'Fallback text selected for over-budget repair.');
record('Validate callback label', 'Callback action retained callback semantics.');
record('Validate callback lacks appointment time', 'Callback did not gain appointment metadata.');
record('Validate appointment label', 'Appointment action retained appointment semantics.');
record('Validate appointment time', 'Appointment retained explicit time metadata.');
record('Keep callback distinct from appointment', 'Kinds and payload shapes remained distinct.');
record('Assemble bounded response fields', 'Response assembly emitted seven approved fields.');
record('Check fallback stability', 'Fallback literal matched policy exactly.');
record('Check fixture determinism', 'Frozen fixture values were stable across reads.');
record('Check source import closure', 'All imports stayed within case-2.');
record('Check network absence', 'No fetch, http client, or socket imports present.');
record('Check secret absence', 'No token, password, or API key literals present.');
record('Check real-data absence', 'Synthetic domains and names only.');
await integrityCheck();
record('Run protected integrity check', 'Protected hashes matched manifest.');
const gates = runGates();
for (const gate of gates) record(`Execute ${gate[0]} ${gate[1]}`, gate[2] ? 'Gate passed.' : 'Gate failed.');
record('Confirm all gates executed', `${gates.length} of ${gateDefinitions.length} gates executed.`);
record('Write machine evidence report', 'Gate report and ledger written to selftest-evidence/.');
record('Confirm no external submission', 'No network, push, merge, or deployment operation performed.');
record('Confirm repaired source remains reproducible', 'Editable source is ready for local commit.');

await mkdir(evidence, { recursive: true });
await writeFile(new URL('./selftest-ledger.json', evidence), JSON.stringify({ notice: 'MACHINE-GENERATED INTERNAL EVIDENCE — USER MUST NARRATE/REWRITE BEFORE SUBMISSION.', steps }, null, 2) + '\n');
console.log(`SELFTEST PASS: ${steps.length} substantive steps; ${gates.length}/${gateDefinitions.length} gates observed`);
